version: '3.8'

services:
  backend:
    build:
      context: ./be
    ports:
      - "3000:3000"
    environment:
      - PORT=3000

  frontend:
    build:
      context: ./fe
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true # Useful for hot-reloading in some Windows/Docker setups
